AgnostiqHQ/covalent-awslambda-plugin

CHANGELOG.md
README.md
covalent_awslambda_plugin/awslambda.py

Fix readme

---

CHANGELOG.md
requirements.txt

Pin covalent version

---

CHANGELOG.md
covalent_awslambda_plugin/awslambda.py

Changed covalent version in templated Dockerfile to correspond to 0.177.0

---

CHANGELOG.md
covalent_awslambda_plugin/awslambda.py
requirements.txt
setup.py
tests/lambda_executor_test.py
tests/requirements.txt

Replaced temp AWSExecutor with correct one

---

CHANGELOG.md
requirements.txt

Updated covalent-aws-plugins version to 0.1.0rc0

---

CHANGELOG.md
covalent_awslambda_plugin/awslambda.py
tests/lambda_executor_test.py

Improve error handling and unblock the main thread

---

CHANGELOG.md
covalent_awslambda_plugin/awslambda.py
covalent_awslambda_plugin/scripts.py
tests/functional_tests/failing_workflow.py
tests/lambda_executor_test.py

Revert to old remote executor api and unblock archive upload

---

CHANGELOG.md
covalent_awslambda_plugin/awslambda.py
requirements.txt

Updated pinned covalent version and aws plugins 

---

CHANGELOG.md
covalent_awslambda_plugin/awslambda.py
requirements.txt

Revert "Updated pinned covalent version and aws plugins  (#40)"

---

CHANGELOG.md
covalent_awslambda_plugin/awslambda.py
covalent_awslambda_plugin/exec.py
tests/lambda_executor_test.py
tests/lambda_handler_test.py

Make execution async

---

CHANGELOG.md
file_dir/file.txt

Remove unused file

---

.github/workflows/tests.yml
CHANGELOG.md
requirements.txt
setup.py

Bumped version of covalent-aws-plugins 

---

CHANGELOG.md
Dockerfile

Updated base aws lambda executor image to explicitly install covalent

---

CHANGELOG.md
covalent_awslambda_plugin/awslambda.py

Fix init method

---

CHANGELOG.md
requirements.txt

Bumped aws plugins version to new stable release

---

.env.example
CHANGELOG.md
tests/functional_tests/README.md

Clean up env file references

---

.github/workflows/license.yml
.github/workflows/release.yml
.github/workflows/tests.yml
CHANGELOG.md

Fix failing workflows

---

.github/workflows/tests.yml
CHANGELOG.md

third times the charm

---

CHANGELOG.md
covalent_awslambda_plugin/awslambda.py

Remove execution_role

---

CHANGELOG.md
tests/functional_tests/basic_workflow_test.py
tests/functional_tests/non_trivial_workflow_test.py

Add print statements to catch covalent version mismatch

---

.github/workflows/docker.yml
CHANGELOG.md

Updated workflow to support configurable covalent version
